version: '3.8'

services:
  mongo:
    image: mongo:5
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: teste_tecnico_shopper_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGODB_URI}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongo

volumes:
  mongo_data:
